*** Variables ***

${CAD_USUARIO.NOME.INPUT}                            css=[data-testid="nome"]
${CAD_USUARIO.EMAIL.INPUT}                           css=[data-testid="nome"]
${CAD_USUARIO.SENHA.INPUT}                           css=[data-testid="nome"]
${CAD_USUARIO.ADMIN.CHECKBOX}                        css=[data-testid="checkbox"]
${CAD_USUARIO.CADASTRAR.BTN}                         css=[data-testid="cadastrarUsuario"]