*** Variables ***
${SIGNUP.NOME.INPUT}                                                    css=[data-testid="nome"]
${SIGNUP.EMAIL.INPUT}                                                   css=[data-testid="email"]
${SIGNUP.SENHA.INPUT}                                                   css=[data-testid="password"]
${SIGNUP.ENTRAR.INPUT}                                                  css=[data-testid="entrar"]
${SIGNUP.CADASTRAR.CHECKBOX}                                            css=[data-testid="checkbox"]
${SIGNUP.CADASTRAR.BUTTON}                                              css=[data-testid="cadastrar"]