name: Pipeline Web e API

on: push

jobs:
  test:
    name: Testes de Web e API
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem Projeto
        uses: actions/checkout@v3

      - name: Configuração do Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Instalar Dependencias do Projeto
        run: |
          pip install robotframework
          pip install robotframework-faker
          pip install -r requirements.txt
      
      - name: Instalar dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Ajustar permissões e normalizar caminhos
        run: |
          find . -type f -exec dos2unix {} +
          find . -type f -exec sed -i 's|\\|/|g' {} +

      - name: Execução dos Testes API
        run: |
          robot --outputdir results/api API/serverestDev/tests

      - name: Execução dos Testes WEB
        run: |
          robot --variable BROWSER:chrome \
                --variable HEADLESS:true \
                --variable USER_DATA_DIR:/tmp/chrome-profile \
                --outputdir results/web tests/serverestDev/e2e

      - name: Salvando Resultado dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultado-testes
          path: results